### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by AndrewMac** [sw-development-services/animate-plugin#1]
Hello there, I'd really like to use this plugin, but when I try to install with composer I get an error:

[InvalidArgumentException]
Could not find a version of package swdevelopment/animate matching your minimum-stability (beta). Require it with an explicit version constraint allowing its desired stability.

I don't particularly want to change my minimum-stability constraints, and I don't particularly want to use anything that has not yet reached at least beta status (preferably stable).

So can you please let me know if it's ready to use, and if so what's the best way to handle this issue with its status? Thanks!

**Comment by timstrawbridge** [comment]
Sorry about that @AndrewMac. I found the problem and fixed it. The package in packagist.org was not synced up with my latest release in github.
