### ISSUE TITLE
Craft 4 Compatibility

### ISSUE THREAD

**Issue by AndrewMac** [sw-development-services/animate-plugin#6]
Hi there, and thanks for your work on this plugin!

I was wondering, though, if you think you might have time to update it for Craft 4?  I know this is not a commercial product, so I understand if you can't.

But if you can't I will start looking to implement my own HTML/CSS/JS solution. Nowhere near as quick and easy, but it would get the job done ;-)

Cheers, Andrew

**Comment by timstrawbridge** [comment]
Thanks for the reminder on this and thank you for using it. I can make some
time to update the plugin sometime this upcoming week.

**Comment by wunderbaresnet** [comment]
Would be great... Thanks.

**Comment by timstrawbridge** [comment]
I have updated and tested the plugin in Craft 4. Please note any problems that come up.

**Comment by ghost** [comment]
Thanks for doing that. I really appreciate it, and happy to say that things are working just fine so far :-)
Cheers, Andrew
