### ISSUE TITLE
Craft 5 compatibility

### ISSUE THREAD

**Issue by AndrewMac** [sw-development-services/animate-plugin#8]
Hi there, and thanks again for your work on this plugin!

It's almost time for another Craft update, so I was wondering if you think you might have time to update it for Craft 5? I know this is not a commercial product, so I understand if you can't.

But if you can't I will start looking to implement my own solution. Nowhere near as quick and easy, but that's okay as long as it would get the job done ;-)

Cheers, Andrew

**Comment by timstrawbridge** [comment]
Hi Andrew,
We'll be able to work on a Craft 5 version next week.

**Comment by AndrewMac** [comment]
Hi Tim
That's great news, thanks so much!
I really appreciate it :-)
Cheers, Andrew

**Comment by timstrawbridge** [comment]
@AndrewMac,
I've updated the plugin to be compatible with Craft CMS 5. Let me know if you come across any problems with it!
~Tim
